export const URL_API_BASE = "http://localhost:8080"
export const ALL_PRODUCTS = "/api/products"
export const LOGIN= "/auth/login"
export const REGISTER = "/auth/register"
export const VERIFY = "/auth/verify"